# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to NPM

on:
  push:
      branches:
        - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
#     - name: npm install
#     - run: npm test
    - name: Publish
      run: npm publish --access public
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_KINGTEZA}}
